[variables]
APP_ENV = "production"
APP_DEBUG = false
SESSION_DRIVER = "database"
SESSION_SECURE_COOKIE = true
QUEUE_CONNECTION = "sync"
CACHE_STORE = "database"
FILESYSTEM_DISK = "local"

[phases.setup]
nixPkgs = ["php82Extensions.pdo_pgsql"]

[phases.build]
cmds = ["npm run build"]
