services:
  - type: web
    name: etb-project
    runtime: docker
    repo: https://github.com/hypeitnow/etb-project
    region: frankfurt
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://etb-project.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: warning
